(function initRepoScoutI18n(globalScope) {
  const MESSAGES = {
    en: {
      popup_main_title: "GitHub Repo Analyzer",
      popup_ai_enhancement: "AI Enhancement",
      popup_enable: "Enable",
      popup_settings: "设置",
      popup_status_prefix: "Status",
      popup_status_off: "Off",
      popup_status_not_configured: "Not Configured",
      popup_status_ready: "Ready",
      popup_status_error: "Error",
      popup_analyzing: "Analyzing...",
      popup_reanalyzing: "Reanalyzing...",
      popup_showing_cached_refreshing: "Showing previous result, refreshing...",
      popup_repo_home_only: "Open this extension on a GitHub repository homepage.",
      popup_analyze_error: "Unable to analyze this repository. Please refresh the current GitHub page and try again.",
      popup_extract_retry_hint: "Page data is temporarily unavailable. Please refresh the current GitHub page and try again.",
      popup_extract_retry_with_cache: "Page data is temporarily unavailable. Please refresh the current GitHub page and try again. (showing previous analysis result).",
      popup_reanalysis_failed_showing_cache: "Reanalysis failed. Showing previous analysis result.",
      popup_last_analyzed_at: "Last analyzed at: {{time}}",
      popup_reanalyze: "Reanalyze",
      popup_reanalyze_busy: "Analyzing...",
      popup_repo_type: "Repo Type",
      popup_what_this_repo_is: "What This Repo Is",
      popup_readme_tldr: "README TL;DR",
      popup_repo_insight: "Repo Insight",
      popup_quick_start: "Quick Start",
      popup_solves_problem: "Solves What Problem",
      popup_project_status: "Project Status",
      popup_popularity: "Popularity",
      popup_tech_stack: "Tech Stack",
      popup_best_for: "Best For",
      popup_steps: "Steps",
      popup_requirements: "Requirements",
      popup_notes: "Notes",
      popup_stars: "Stars",
      popup_forks: "Forks",
      popup_level: "Level",
      popup_unknown: "Unknown",
      popup_no_audience: "No clear audience inferred from current repository data.",
      popup_no_readme_tldr: "No README TL;DR extracted.",
      popup_no_startup_steps: "No startup steps detected.",
      popup_no_requirements: "No explicit requirements detected.",
      popup_no_notes: "No special notes.",
      popup_project_activity_limited: "Project activity information is limited.",
      repo_type_runnable_project: "Runnable Project",
      repo_type_library_package: "Library Package",
      repo_type_template_example: "Template / Example",
      repo_type_fork_or_special: "Fork / Special",
      project_status_active: "Active",
      project_status_moderate: "Moderate",
      project_status_low_activity: "Low Activity",
      project_status_archived: "Archived",
      project_status_unknown: "Unknown",
      popularity_level_high: "High",
      popularity_level_medium: "Medium",
      popularity_level_low: "Low",
      popularity_level_unknown: "Unknown",
      source_rule_based: "Rule-based",
      source_ai_generated: "AI-generated",
      source_ai_enhanced: "AI-enhanced",
      source_fallback: "Fallback",
      source_rule_based_title: "Extracted from GitHub page structure, repository files, or heuristic rules.",
      source_ai_generated_title: "Generated by AI from repository facts and README context.",
      source_ai_enhanced_title: "Based on extracted facts, then rewritten or improved by AI.",
      source_fallback_title: "AI was unavailable, so a rule-based fallback result is shown.",
      options_output_language: "Output Language",
      options_lang_auto: "Auto",
      options_lang_en: "英文",
      options_lang_zh: "中文",
      options_speed_warning: "Note: Enabling AI analysis may significantly slow down analysis speed.",
      options_unsaved_changes: "You have unsaved changes. Click 保存 to apply them.",
      options_test_success_need_save: "Connection successful. Remember to click 保存 to apply these settings."
    },
    zh: {
      popup_main_title: "GitHub 仓库分析",
      popup_ai_enhancement: "AI 增强",
      popup_enable: "启用",
      popup_settings: "设置",
      popup_status_prefix: "状态",
      popup_status_off: "关闭",
      popup_status_not_configured: "未配置",
      popup_status_ready: "可用",
      popup_status_error: "错误",
      popup_analyzing: "分析中...",
      popup_reanalyzing: "重新分析中...",
      popup_showing_cached_refreshing: "正在显示上次结果，并刷新中...",
      popup_repo_home_only: "请在 GitHub 仓库主页打开此扩展。",
      popup_analyze_error: "无法分析该仓库。请先刷新当前 GitHub 页面后再试。",
      popup_extract_retry_hint: "页面信息暂不可用，请刷新当前 GitHub 页面后再试。",
      popup_extract_retry_with_cache: "页面信息暂不可用，请刷新当前 GitHub 页面后再试。（当前显示上次分析结果）",
      popup_reanalysis_failed_showing_cache: "本次重新分析失败，当前显示上次分析结果。",
      popup_last_analyzed_at: "上次分析时间：{{time}}",
      popup_reanalyze: "重新分析",
      popup_reanalyze_busy: "分析中...",
      popup_repo_type: "仓库类型",
      popup_what_this_repo_is: "这个仓库是什么",
      popup_readme_tldr: "README 摘要",
      popup_repo_insight: "仓库洞察",
      popup_quick_start: "快速启动",
      popup_solves_problem: "解决了什么问题",
      popup_project_status: "项目状态",
      popup_popularity: "受欢迎程度",
      popup_tech_stack: "技术栈",
      popup_best_for: "适用人群",
      popup_steps: "步骤",
      popup_requirements: "依赖要求",
      popup_notes: "注意事项",
      popup_stars: "Stars",
      popup_forks: "Forks",
      popup_level: "等级",
      popup_unknown: "未知",
      popup_no_audience: "基于当前仓库信息，暂未推断出明确适用人群。",
      popup_no_readme_tldr: "未提取到 README 摘要。",
      popup_no_startup_steps: "未识别到启动步骤。",
      popup_no_requirements: "未识别到明确依赖要求。",
      popup_no_notes: "暂无特别说明。",
      popup_project_activity_limited: "项目活跃度信息有限。",
      repo_type_runnable_project: "可运行项目",
      repo_type_library_package: "库/包项目",
      repo_type_template_example: "模板/示例",
      repo_type_fork_or_special: "Fork/特殊仓库",
      project_status_active: "活跃",
      project_status_moderate: "一般",
      project_status_low_activity: "低活跃",
      project_status_archived: "已归档",
      project_status_unknown: "未知",
      popularity_level_high: "高",
      popularity_level_medium: "中",
      popularity_level_low: "低",
      popularity_level_unknown: "未知",
      source_rule_based: "规则生成",
      source_ai_generated: "AI 生成",
      source_ai_enhanced: "AI 增强",
      source_fallback: "回退结果",
      source_rule_based_title: "来自 GitHub 页面结构、仓库文件或规则判断。",
      source_ai_generated_title: "由 AI 基于仓库事实和 README 上下文生成。",
      source_ai_enhanced_title: "基于规则提取结果，再由 AI 重写或增强。",
      source_fallback_title: "AI 当前不可用，因此展示规则回退结果。",
      options_output_language: "输出语言",
      options_lang_auto: "自动",
      options_lang_en: "English",
      options_lang_zh: "中文",
      options_speed_warning: "提示：启用 AI 分析可能会显著降低分析速度。",
      options_unsaved_changes: "你有未保存的修改，请点击“保存”应用设置。",
      options_test_success_need_save: "连接成功。请记得点击“保存”使设置生效。"
    }
  };

  function normalizeLanguageChoice(value) {
    const lowered = (value || "").toString().trim().toLowerCase();
    if (lowered === "zh" || lowered === "en" || lowered === "auto") {
      return lowered;
    }
    return "auto";
  }

  function normalizeResolvedLanguage(value) {
    const lowered = (value || "").toString().trim().toLowerCase();
    return lowered === "zh" ? "zh" : "en";
  }

  function getBrowserLanguageHint() {
    if (typeof chrome !== "undefined" && chrome?.i18n?.getUILanguage) {
      return chrome.i18n.getUILanguage();
    }
    if (typeof navigator !== "undefined") {
      return navigator.language || "";
    }
    return "";
  }

  function detectLanguageFromText(text) {
    const raw = (text || "").toString();
    if (!raw.trim()) {
      return "";
    }

    const sample = raw.slice(0, 12000);
    const zhMatches = sample.match(/[\u4e00-\u9fff]/g) || [];
    const enMatches = sample.match(/[A-Za-z]/g) || [];
    const zhCount = zhMatches.length;
    const enCount = enMatches.length;

    if (zhCount >= 24 && zhCount * 2 >= enCount) {
      return "zh";
    }
    if (enCount >= 120 && zhCount <= 12) {
      return "en";
    }
    if (zhCount >= 10 && enCount < 50) {
      return "zh";
    }
    if (enCount >= 60 && zhCount === 0) {
      return "en";
    }
    return "";
  }

  function detectRepoLanguage(payload) {
    const source = payload && typeof payload === "object" ? payload : {};
    const text = [
      source.readmeText || "",
      source.description || "",
      Array.isArray(source.topics) ? source.topics.join(" ") : ""
    ]
      .join("\n")
      .trim();
    return detectLanguageFromText(text);
  }

  function resolveLanguage(preferredLanguage, payload, browserLanguageHint) {
    const preferred = normalizeLanguageChoice(preferredLanguage);
    if (preferred === "zh" || preferred === "en") {
      return preferred;
    }

    const detected = detectRepoLanguage(payload);
    if (detected) {
      return detected;
    }

    const browserHint = (browserLanguageHint || getBrowserLanguageHint() || "").toLowerCase();
    if (browserHint.startsWith("zh")) {
      return "zh";
    }
    return "en";
  }

  function formatMessage(template, params) {
    if (!params || typeof params !== "object") {
      return template;
    }
    return template.replace(/\{\{(\w+)\}\}/g, (_match, key) => {
      const value = params[key];
      return value === undefined || value === null ? "" : String(value);
    });
  }

  function t(language, key, params) {
    const resolvedLanguage = normalizeResolvedLanguage(language);
    const text = MESSAGES[resolvedLanguage]?.[key] || MESSAGES.en[key] || key;
    return formatMessage(text, params);
  }

  function localizeValue(value, language) {
    if (!value || typeof value !== "object" || Array.isArray(value)) {
      return value;
    }
    const resolvedLanguage = normalizeResolvedLanguage(language);
    if (typeof value[resolvedLanguage] === "string") {
      return value[resolvedLanguage];
    }
    if (typeof value.en === "string") {
      return value.en;
    }
    if (typeof value.zh === "string") {
      return value.zh;
    }
    return value;
  }

  globalScope.RepoScoutI18n = {
    MESSAGES,
    normalizeLanguageChoice,
    normalizeResolvedLanguage,
    resolveLanguage,
    detectRepoLanguage,
    localizeValue,
    t
  };
})(self);
